//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBFirstApproaches
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public EmployeeDetail()
        {
            this.Employees = new HashSet<EmployeeDetail>();
        }
    
        public int EmpId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        public virtual ICollection<EmployeeDetail> Employees { get; set; }
        public virtual EmployeeDetail Manager { get; set; }
    }
}
