//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DBFirstApproaches
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
    }
}
